/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.iCet.iBurgerShop.view;

/**
 *
 * @author chama
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewCust = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        addCustomerBtn = new javax.swing.JButton();
        searchCustomer = new javax.swing.JButton();
        updateCustomer = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewCust.setBackground(new java.awt.Color(204, 204, 255));
        viewCust.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        viewCust.setText("View Customers");
        viewCust.setAutoscrolls(true);
        viewCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCustActionPerformed(evt);
            }
        });
        getContentPane().add(viewCust, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 320, -1));

        deleteBtn.setBackground(new java.awt.Color(204, 204, 255));
        deleteBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        deleteBtn.setText("Delete Customer");
        deleteBtn.setAutoscrolls(true);
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 320, -1));

        addCustomerBtn.setBackground(new java.awt.Color(204, 204, 255));
        addCustomerBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addCustomerBtn.setText("Add Customer");
        addCustomerBtn.setAutoscrolls(true);
        addCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addCustomerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 320, -1));

        searchCustomer.setBackground(new java.awt.Color(204, 204, 255));
        searchCustomer.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        searchCustomer.setText("Search Customers");
        searchCustomer.setAutoscrolls(true);
        searchCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCustomerActionPerformed(evt);
            }
        });
        getContentPane().add(searchCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 320, -1));

        updateCustomer.setBackground(new java.awt.Color(204, 204, 255));
        updateCustomer.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        updateCustomer.setText("Update Customer");
        updateCustomer.setAutoscrolls(true);
        updateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCustomerActionPerformed(evt);
            }
        });
        getContentPane().add(updateCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 320, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 52)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("IHungry Burger Shop");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        jLabel2.setBackground(new java.awt.Color(102, 204, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iCet/iBurgerShop/view/Background.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 1170, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCustActionPerformed
       new ViewCustomer().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_viewCustActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        new DeleteCustomer().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void addCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerBtnActionPerformed
        new AddCustomer().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_addCustomerBtnActionPerformed

    private void searchCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCustomerActionPerformed
         new SearchCustomer().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_searchCustomerActionPerformed

    private void updateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCustomerActionPerformed
       new UpdateCustomer().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_updateCustomerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCustomerBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton searchCustomer;
    private javax.swing.JButton updateCustomer;
    private javax.swing.JButton viewCust;
    // End of variables declaration//GEN-END:variables
}
